apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: build-suite-test-component-git-source-mxle
  namespace: appstudio-e2e-test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: build-suite-test-application-wqaz
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: build-suite-test-component-git-source-mxle
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: build-suite-test-component-git-source-mxle-
      labels:
        build.appstudio.openshift.io/application: build-suite-test-application-wqaz
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: build-suite-test-component-git-source-mxle
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: appstudio-e2e-test
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-hello-world
      - name: output-image
        value: quay.io/psturc/test-images:648a01c55f664b188ecc4b626b66149b-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:ad4c34b71d468a991450b0091cd96765471ed82d
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: build-suite-test-component-git-source-mxle/$(tt.params.git-revision)
    status: {}
status: {}
